### ISSUE TITLE
normalize icon set

### ISSUE THREAD

**Issue by thunder-red-star** [achen318/junior.stuysu.org#13]
![logo-youtube](https://user-images.githubusercontent.com/67127399/204116977-41779c7e-2c5d-4c94-9bad-159bb0f2a652.svg)
![logo-github](https://user-images.githubusercontent.com/67127399/204116979-b486b62f-8cae-4dba-985e-145b6e12b21b.svg)
![mail-outline](https://user-images.githubusercontent.com/67127399/204116980-06c51f65-59e4-485e-b4cc-9b733efc826d.svg)
![logo-discord](https://user-images.githubusercontent.com/67127399/204116981-486fb566-9781-46a0-9550-6dbe75f92efc.svg)

take these ionicons because the some-color some-not-color icons are making my ocd flare up

**Comment by thunder-red-star** [comment]
![logo-tiktok](https://user-images.githubusercontent.com/67127399/204117013-ec20ce41-7795-450c-a233-d3f5c4fbae22.svg)
![logo-linkedin](https://user-images.githubusercontent.com/67127399/204117014-91f0a65b-707a-4e61-a407-4f17981dbdbb.svg)
![logo-facebook](https://user-images.githubusercontent.com/67127399/204117015-94c2e44d-c16c-406e-aeb9-39b35527bedd.svg)
![logo-instagram](https://user-images.githubusercontent.com/67127399/204117016-d924f3e3-6e47-48db-b7f7-3aa2a69298b8.svg)

more iconions

**Comment by achen318** [comment]
merged
