### ISSUE TITLE
calendar component

### ISSUE THREAD

**Issue by achen318** [achen318/junior.stuysu.org#2]

**Comment by thunder-red-star** [comment]
fully functional calendar?!

**Comment by thunder-red-star** [comment]
@robobun

```js
console.log("fully functional calendar?!");
```

**Comment by robobun** [comment]
@thunder-red-star here you go!
```tsx
fully functional calendar?!
```
<details>
  <summary>Code</summary>
  
```tsx
console.log("fully functional calendar?!");
```
</details>

_Ran using the latest build of Bun, an all-in-one JavaScript runtime._

**Comment by thunder-red-star** [comment]
ok bun

**Comment by SJS830** [comment]
@robobun 
```js
console.log("ok william v.");
```

**Comment by thunder-red-star** [comment]
@robobun 

```js
console.log("😡 that was my secret")
```

**Comment by robobun** [comment]
@thunder-red-star here you go!
```tsx
堽帡 that was my secret
```
<details>
  <summary>Code</summary>
  
```tsx
console.log("😡 that was my secret")
```
</details>

_Ran using the latest build of Bun, an all-in-one JavaScript runtime._

**Comment by thunder-red-star** [comment]
[# https://github.com/robobun/robobun/issues/2](https://github.com/robobun/robobun/issues/2)
